# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb-namespace
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
