apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: mongodb-namespace
data:
  database_url: mongodb-service
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: mongodb-namespace
spec:
  selector:
    app: mongodb-express
  type: LoadBalancer # Uncomment for external service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 # Uncomment for external service
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: mongodb-namespace
spec:
  selector:
    app: flask-app
  type: LoadBalancer # Uncomment for external service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001 # Uncomment for external service